[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.0"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 127
exclude = ["gridient/_version.py"]

[tool.ruff.format]
quote-style = "double"

[tool.setuptools_scm]
write_to = "gridient/_version.py" 